{
 "title": "GPU Mangagement",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "GPU MEMORY",
   "type": "table",
   "gridPos": { "h": 20, "w": 13, "x": 0, "y": 0 },
   "targets": [
    { "expr": "DCGM_FI_DEV_FB_USED", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usages",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Counts",
   "type": "table",
   "gridPos": { "h": 6, "w": 10, "x": 13, "y": 7 },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{mode=\"idle\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 7, "w": 10, "x": 13, "y": 13 },
   "targets": [
    { "expr": "node_memory_MemTotal_bytes ", "legendFormat": "__auto" },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}